### ISSUE TITLE
Coloring individual bars in a bar chart and with a legend showing

### ISSUE THREAD

**Issue by eddy-oj** [plotly/python-user-guide#21]
How do we code a bar chart in python so that bars are colored by categories representing thresholds such as, 'The Good’, ‘The Bad’ and ‘The Ugly’ using the colors 'green, ‘orange’ and ‘red’?

A specific example of what is missing in the user guide is the ‘Customizing Individual Bar Colors’ example in the docs - colored bar charts should rarely come without a legend yet this isn't shown in the docs and I can't suss it out easily. 

How does one show the legend whilst retaining the current order of the bars?

**Comment by etpinard** [comment]
Questions of the likes should be asked on https://community.plot.ly/c/api/python

Thank you.

**Comment by eddy-ojb** [comment]
Not really. This is a basic function of a bar chart that is standard across other dashboarding software. It needs to be documented.
